### ISSUE TITLE
Testing without London enabled

### ISSUE THREAD

**Issue by miohtama** [ethereum/eth-tester#233]
### What was wrong?

In the README it says `Ethereum tester uses the London fork rules, starting at block 0.`

Is it possible still to run Ethereum Tester with the legacy gas rules in place and London hard fork disabled?

**Comment by fselmo** [comment]
Hey @miohtama. Since the backend is configurable, I believe this can get you what you want:

``` python
from eth.vm.forks import FrontierVM  # or any other hard fork VM here whos rules you want to test
from eth_tester import EthereumTester, PyEVMBackend
from web3 import EthereumTesterProvider, Web3


backend = PyEVMBackend(vm_configuration=(
    (0, FrontierVM),
))

frontier_eth_tester_provider = EthereumTesterProvider(
    ethereum_tester=EthereumTester(backend=backend)
)

# if testing with web3
w3 = Web3(frontier_eth_tester_provider)
```

We should probably document this somewhere though 🤔. I'm surprised it isn't somewhere already. I will leave this open in case someone is able to get to it. I just realized Arrow Glacier isn't pulled into eth-tester yet so maybe I can scoop this doc update in as well.

**Comment by miohtama** [comment]
Thank you so much @fselmo 

After I get this running, I will do some documentation work.
