### ISSUE TITLE
Make block gas limit configurable

### ISSUE THREAD

**Issue by palango** [ethereum/eth-tester#88]
* Version: 0.1.0-beta.24
* Python: 3.6
* OS: osx

### What was wrong?

Currently the block gas limit is hard coded: https://github.com/ethereum/eth-tester/blob/b9ad39a9ee8ef041d2ca2d2c2d1d1e28d3f36da9/eth_tester/backends/pyevm/main.py#L66

This fails some tests with larger contracts and should be made configurable. Also increasing the default might make sense, the mainnet blocks have been bigger than 6 million gas for some time.

### How can it be fixed?

Make the block gas limit configurable and think about increasing the default value.

**Comment by voith** [comment]
@palango just curious to know how you'd make such constants configurable. Are you thinking of something like django settings, env variables or providing config as a parameter to the entry point(I'm fairly new to this project and I don't know the entry point)?

**Comment by pipermerriam** [comment]
@palango 👍 to making genesis parameters configurable.

I'd rather do this as an initialization parameter to the `PyEVMBackend` to allow supplying `genesis_params`.  I think adding `genesis_state` would also be beneficial, but that part *could* be more tricky since we also have to initialize the *default accounts* and there is a question of whether `genesis_state` should be merged with the default account state, or whether it should fully override it...

https://github.com/ethereum/eth-tester/blob/b9ad39a9ee8ef041d2ca2d2c2d1d1e28d3f36da9/eth_tester/backends/pyevm/main.py#L140-L142

**Comment by palango** [comment]
Making the genesis parameters constructor parameters sounds good and usable to me. Adding genesis state would surely be useful with large contract systems. Here it would be good if it is nicely integrated with the snapshot system, i.e. using snapshots of a chain as genesis state.

**Comment by pipermerriam** [comment]
@palango do you think you have enough context to *either*:

- update this issue with a reasonable spec for providing genesis params
- create a new issue speccing thing out?

RE: snapshots, I do think that's a solid API for `eth-tester` to implement but I'd push that out into a separate issue/ticket.

**Comment by palango** [comment]
@pipermerriam I'm in vacation right now and will look into this afterwards.

**Comment by carver** [comment]
This is possible (though not pleasant yet), so I'll close. There's a tracking issue for making it better: #129
